[2023-06-07T18:08:07.935+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T15:00:00+00:00 [queued]>
[2023-06-07T18:08:07.953+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T15:00:00+00:00 [queued]>
[2023-06-07T18:08:07.954+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:08:08.094+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 15:00:00+00:00
[2023-06-07T18:08:08.100+0300] {standard_task_runner.py:57} INFO - Started process 38993 to run task
[2023-06-07T18:08:08.105+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T15:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpa865dbhh']
[2023-06-07T18:08:08.108+0300] {standard_task_runner.py:85} INFO - Job 160: Subtask get_data
[2023-06-07T18:08:08.300+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T15:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:08:08.542+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T15:00:00+00:00'
[2023-06-07T18:08:16.328+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:08:16.496+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230606T150000, start_date=20230607T150807, end_date=20230607T150816
[2023-06-07T18:08:16.523+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 160 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 38993)
[2023-06-07T18:08:16.570+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:08:16.662+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:45:03.680+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T15:00:00+00:00 [queued]>
[2023-06-07T18:45:03.710+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T15:00:00+00:00 [queued]>
[2023-06-07T18:45:03.710+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:45:03.756+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 15:00:00+00:00
[2023-06-07T18:45:03.764+0300] {standard_task_runner.py:57} INFO - Started process 53529 to run task
[2023-06-07T18:45:03.774+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T15:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmp3cjqyv2w']
[2023-06-07T18:45:03.777+0300] {standard_task_runner.py:85} INFO - Job 228: Subtask get_data
[2023-06-07T18:45:03.988+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T15:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:45:04.549+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T15:00:00+00:00'
[2023-06-07T18:45:04.550+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:45:04.583+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T150000, start_date=20230607T154503, end_date=20230607T154504
[2023-06-07T18:45:04.673+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:45:04.794+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
