[2023-06-07T18:29:29.731+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data manual__2023-06-07T15:29:28.518886+00:00 [queued]>
[2023-06-07T18:29:29.750+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data manual__2023-06-07T15:29:28.518886+00:00 [queued]>
[2023-06-07T18:29:29.751+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:29:29.794+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 15:29:28.518886+00:00
[2023-06-07T18:29:29.801+0300] {standard_task_runner.py:57} INFO - Started process 46966 to run task
[2023-06-07T18:29:29.809+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'manual__2023-06-07T15:29:28.518886+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpgrf6aaac']
[2023-06-07T18:29:29.815+0300] {standard_task_runner.py:85} INFO - Job 186: Subtask get_data
[2023-06-07T18:29:29.941+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data manual__2023-06-07T15:29:28.518886+00:00 [running]> on host mutwiri
[2023-06-07T18:29:30.337+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T15:29:28.518886+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-07T15:29:28.518886+00:00'
[2023-06-07T18:29:30.337+0300] {templating_using_python.py:16} INFO - The execution date of this flow is 2023-06-07
[2023-06-07T18:29:30.338+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 17, in _get_data
    year, month, day, hour, *_ = ds.timetuple()
AttributeError: 'str' object has no attribute 'timetuple'
[2023-06-07T18:29:30.364+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230607T152928, start_date=20230607T152929, end_date=20230607T152930
[2023-06-07T18:29:30.390+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 186 for task get_data ('str' object has no attribute 'timetuple'; 46966)
[2023-06-07T18:29:30.427+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:29:30.462+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
