[2023-06-07T18:07:54.394+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T08:00:00+00:00 [queued]>
[2023-06-07T18:07:54.430+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T08:00:00+00:00 [queued]>
[2023-06-07T18:07:54.431+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:07:54.562+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 08:00:00+00:00
[2023-06-07T18:07:54.569+0300] {standard_task_runner.py:57} INFO - Started process 38364 to run task
[2023-06-07T18:07:54.581+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T08:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpzjn95jn6']
[2023-06-07T18:07:54.585+0300] {standard_task_runner.py:85} INFO - Job 153: Subtask get_data
[2023-06-07T18:07:54.810+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T08:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:07:55.214+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T08:00:00+00:00'
[2023-06-07T18:08:00.179+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:08:00.327+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230606T080000, start_date=20230607T150754, end_date=20230607T150800
[2023-06-07T18:08:00.367+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 153 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 38364)
[2023-06-07T18:08:00.408+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:08:00.471+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:44:56.958+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T08:00:00+00:00 [queued]>
[2023-06-07T18:44:56.981+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T08:00:00+00:00 [queued]>
[2023-06-07T18:44:56.981+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:44:57.020+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 08:00:00+00:00
[2023-06-07T18:44:57.027+0300] {standard_task_runner.py:57} INFO - Started process 53167 to run task
[2023-06-07T18:44:57.033+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T08:00:00+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpua7g2fjs']
[2023-06-07T18:44:57.037+0300] {standard_task_runner.py:85} INFO - Job 221: Subtask get_data
[2023-06-07T18:44:57.227+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T08:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:44:57.973+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T08:00:00+00:00'
[2023-06-07T18:44:57.973+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:44:58.053+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T080000, start_date=20230607T154456, end_date=20230607T154458
[2023-06-07T18:44:58.293+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:44:58.434+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
