[2023-06-07T18:08:11.485+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T02:00:00+00:00 [queued]>
[2023-06-07T18:08:11.495+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T02:00:00+00:00 [queued]>
[2023-06-07T18:08:11.495+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:08:11.538+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 02:00:00+00:00
[2023-06-07T18:08:11.544+0300] {standard_task_runner.py:57} INFO - Started process 39256 to run task
[2023-06-07T18:08:11.550+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T02:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpse5m2a5g']
[2023-06-07T18:08:11.553+0300] {standard_task_runner.py:85} INFO - Job 171: Subtask get_data
[2023-06-07T18:08:11.658+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T02:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:08:11.934+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T02:00:00+00:00'
[2023-06-07T18:08:16.994+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:08:17.142+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230607T020000, start_date=20230607T150811, end_date=20230607T150817
[2023-06-07T18:08:17.177+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 171 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 39256)
[2023-06-07T18:08:17.222+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:08:17.255+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:45:09.924+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T02:00:00+00:00 [queued]>
[2023-06-07T18:45:09.943+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T02:00:00+00:00 [queued]>
[2023-06-07T18:45:09.944+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:45:09.987+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 02:00:00+00:00
[2023-06-07T18:45:09.993+0300] {standard_task_runner.py:57} INFO - Started process 53959 to run task
[2023-06-07T18:45:10.009+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T02:00:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpsrvwy32t']
[2023-06-07T18:45:10.013+0300] {standard_task_runner.py:85} INFO - Job 239: Subtask get_data
[2023-06-07T18:45:10.230+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T02:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:45:11.099+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T02:00:00+00:00'
[2023-06-07T18:45:11.100+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:45:11.140+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230607T020000, start_date=20230607T154509, end_date=20230607T154511
[2023-06-07T18:45:11.213+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:45:11.269+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
