[2023-06-02T08:37:11.354+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions.get_images manual__2023-06-02T05:37:06.856657+00:00 [queued]>
[2023-06-02T08:37:11.377+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions.get_images manual__2023-06-02T05:37:06.856657+00:00 [queued]>
[2023-06-02T08:37:11.378+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-02T08:37:11.440+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_images> on 2023-06-02 05:37:06.856657+00:00
[2023-06-02T08:37:11.452+0300] {standard_task_runner.py:57} INFO - Started process 11161 to run task
[2023-06-02T08:37:11.471+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'space_missions', 'get_images', 'manual__2023-06-02T05:37:06.856657+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/space_missions.py', '--cfg-path', '/tmp/tmpvikfjsbe']
[2023-06-02T08:37:11.479+0300] {standard_task_runner.py:85} INFO - Job 23: Subtask get_images
[2023-06-02T08:37:11.598+0300] {task_command.py:410} INFO - Running <TaskInstance: space_missions.get_images manual__2023-06-02T05:37:06.856657+00:00 [running]> on host mutwiri
[2023-06-02T08:37:11.909+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='space_missions' AIRFLOW_CTX_TASK_ID='get_images' AIRFLOW_CTX_EXECUTION_DATE='2023-06-02T05:37:06.856657+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-02T05:37:06.856657+00:00'
[2023-06-02T08:37:13.683+0300] {logging_mixin.py:149} INFO - Downloaded https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20210922155355.jpeg to ../images/falcon2520925_image_20210922155355.jpeg
[2023-06-02T08:37:15.794+0300] {logging_mixin.py:149} INFO - Downloaded https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20230503085110.png to ../images/falcon2520925_image_20230503085110.png
[2023-06-02T08:37:18.022+0300] {logging_mixin.py:149} INFO - Downloaded https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/falcon_9_block__image_20210506060831.jpg to ../images/falcon_9_block__image_20210506060831.jpg
[2023-06-02T08:37:20.442+0300] {logging_mixin.py:149} INFO - Downloaded https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/ariane_5_eca25_image_20200220090552.jpeg to ../images/ariane_5_eca25_image_20200220090552.jpeg
[2023-06-02T08:37:22.597+0300] {logging_mixin.py:149} INFO - Downloaded https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/falcon_9_block__image_20210506060831.jpg to ../images/falcon_9_block__image_20210506060831.jpg
[2023-06-02T08:37:25.827+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/space_missions.py", line 41, in get_images
    with open (target_file, "wb" ) as target:
FileNotFoundError: [Errno 2] No such file or directory: '../images/delta_iv_heavy_image_20210426103838.jpg'
[2023-06-02T08:37:25.863+0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=space_missions, task_id=get_images, execution_date=20230602T053706, start_date=20230602T053711, end_date=20230602T053725
[2023-06-02T08:37:25.932+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task get_images ([Errno 2] No such file or directory: '../images/delta_iv_heavy_image_20210426103838.jpg'; 11161)
[2023-06-02T08:37:25.978+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-02T08:37:26.038+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
